### ISSUE TITLE
Missing Network Files

### ISSUE THREAD

**Issue by autominded** [carloscaetano/skeleton-images#1]
Please add the necessary network files, im looking forward. I can contribute aswell in getting the repository documented.

**Comment by carloscaetano** [comment]
As mentioned in the paper, the network employed is a modified version from Li et al., 2017 (Skeleton-based Action Recognition with Convolutional Neural Networks). You can find their implementation code in Keras on Github: https://github.com/XiaoCode-er/Two-Stream-CNN/blob/master/networks/basic_4_fc.py

In our experiments we used just one stream and simply removed the Fully Connected (FC) layers 2 and 3.
