### ISSUE TITLE
Document Format of skeleton file to pass in

### ISSUE THREAD

**Issue by jordanhart** [carloscaetano/skeleton-images#3]
Hi!

I am trying to use this on other datasets (JHMDB, UTKinect-Action3D Dataset). Would it be possible to document the skeleton file format in the README or document another way to pass in or use other skeleton data?

Thanks!

**Comment by carloscaetano** [comment]
The skeleton format should follow the NTU 60 or NTU 120 format. Please, check this for understanding:
https://github.com/shahroudy/NTURGB-D/blob/master/Matlab/read_skeleton_file.m

**Comment by jordanhart** [comment]
Thanks!
