### ISSUE TITLE
If there are two bodies in a sequence, how do you train a network. 

### ISSUE THREAD

**Issue by youjiangithub** [carloscaetano/skeleton-images#5]
If there are two bodies in a sequence, how do you train a network. Are two human skeleton images input into the network separately for training?

**Comment by carloscaetano** [comment]
@youjiangithub , as mentioned in the papers, to cope with actions involving multi-person interaction (e.g., shaking hands), we apply a common choice in the literature which is to stack skeleton image representations of different people as the network input.
